#!/usr/bin/env bash
# Build the static playground into playground/dist/: the wasm checker, the page, and an
# examples.js baked from a curated subset of examples/ (pure-checkable programs only).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

cargo build -p blight-playground --release --target wasm32-unknown-unknown
mkdir -p playground/dist
cp target/wasm32-unknown-unknown/release/blight_playground.wasm playground/dist/
cp playground/index.html playground/playground.js playground/worker.js playground/dist/

# Curated examples: small, self-contained, checkable without FileIO/graphics.
{
  echo "// generated by playground/build.sh — do not edit"
  echo "export const EXAMPLES = {"
  for f in hello_nat records_demo equations list_sum vec_head safe_head either_compute; do
    printf '  %s: ' "\"$f.bl\""
    node -e 'const fs=require("fs");process.stdout.write(JSON.stringify(fs.readFileSync(process.argv[1],"utf8")))' "examples/$f.bl"
    echo ","
  done
  echo "};"
} > playground/dist/examples.js
echo "playground built: playground/dist/"
